{% set name = "ftfy" %}
{% set version = "6.3.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9b3c3d90f84fb267fe64d375a07b7f8912d817cf86009ae134aa03e1819506ec

build:
  skip: True  # [py<39]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  entry_points:
    - ftfy = ftfy.cli:main

requirements:
  host:
    - python
    - pip
    - hatchling
  run:
    - python
    - wcwidth

test:
  source_files:
    - tests
  imports:
    - ftfy
    - ftfy.bad_codecs.utf8_variants
    - ftfy.chardata
    - ftfy.fixes
  requires:
    - pytest
    - pip
  commands:
    - pip check
    - pytest -v tests

about:
  home: https://ftfy.readthedocs.io
  license: Apache-2.0
  license_file: LICENSE.txt
  license_family: Apache
  summary: Fixes mojibake and other glitches in Unicode text, after the fact
  description: |
    The goal of ftfy is to take in bad Unicode and output good
    Unicode, for use in your Unicode-aware code.
  dev_url: https://github.com/rspeer/python-ftfy
  doc_url: https://ftfy.readthedocs.io

extra:
  recipe-maintainers:
    - rmax
