{% set name = "ftfy" %}
{% set version = "5.5.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 525ea45a871f52ddb170e66b01f35f1b3022995016c81efa305e628937b85443

build:
  number: 1000
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  skip: True  # [py2k or py>36]
  entry_points:
    - ftfy = ftfy.cli:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    # Required for loading package data via `pkg_resources` module.
    - setuptools
    - wcwidth

test:
  requires:
    - nose
  source_files:
    - tests
  commands:
    - nosetests -v tests  # [unix]
    # CLI tests fail on windows.
    - nosetests -v -e test_cli tests  # [win]

about:
  home: https://github.com/LuminosoInsight/python-ftfy/
  license: MIT
  license_file: LICENSE.txt
  summary: Fixes some problems with Unicode text after the fact
  dev_url: https://github.com/LuminosoInsight/python-ftfy
  doc_url: http://ftfy.readthedocs.io/

extra:
  recipe-maintainers:
    - rmax
