{% set name = "ftfy" %}
{% set version = "4.4.3" %}
{% set sha256sum = "3c0066db64a98436e751e56414f03f1cdea54f29364c0632c141c36cca6a5d94" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - ftfy = ftfy.cli:main

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    # Required for loading package data via `pkg_resources` module.
    - setuptools
    - html5lib
    - wcwidth

test:
  imports:
    - ftfy
    - ftfy.bad_codecs
    - ftfy.build_data
    - ftfy.chardata
    - ftfy.cli
    - ftfy.fixes
    - ftfy.formatting

  commands:
    - ftfy -h

about:
  home: https://github.com/LuminosoInsight/python-ftfy/
  license: MIT
  license_file: LICENSE.txt
  summary: Fixes some problems with Unicode text after the fact
  dev_url: https://github.com/LuminosoInsight/python-ftfy
  doc_url: http://ftfy.readthedocs.io/

extra:
  recipe-maintainers:
    - rolando
    - nehaljwani
