travis:
  secure:
    BINSTAR_TOKEN: OWP8Yz+rtsj3rB9w/VCELOmznYPXJ8qKQC3325t+F/b3zxG7ibrClIyRe8WcB0QTtkhZy8K10rSLFaCreZjAuMFw3XGSJ6NbAm/vMEhaw4nwZMkP9ntGWTDK8XnbE9sndc851EC6k1UwqZRATUUN08X/bge0fOv0fePiY1ZYqSn3A0wWu9j1MwsQozwz4U8zYyS3PtyAhkU6cJ6DU0Ssq3cAqlOJLGzG5CR5aqTP5varK9rCzibjYDNas8pxeFwXb+4IzUhAmhrHCWYch2Z6bcGKVo8nqihSDel4bWh8kGR4jDkEP9zKDd8znNQO1+S2YxRhd2rm4GlH2/gyqhA39RSJe227nHgMSkk40+eEyY11BbsO5Jzi5qOKRTQ83Tc+tWPuqyRiAwEJ6QDSeZeyrJ47e07zI689xsZX/H8z4VwFuBKWPE7cP+/aUBdt0Z3yJ6242b1da9aYrvzgxzV6hvnel1VSv2qDElvmdxtNxmMzt745tIeXYhDGd68NrdqiCaRHxsHA27dOdpym0Zgej85YcFfC7mXKoqDbK4A+IuM3kHh0w7IWJb75IFRuk5OFmJ/tqXEISdSzT6n0LM9yDk0YIV7369uK3wN2W4xGVZHu77a1cIV9IMJYA1nmnaVHVNKGYOOcNtH4vbhCtVy8ImE/8CZVl8JTNpIHLFrWDII=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
