travis:
  secure:
    BINSTAR_TOKEN: qKap503H3eltR8qyby7CMN6ruIe1NkKXcx7iBIujrvjoUl/Jn0qGpyFYUQ9PykvSYNq/bitxKSi7m4T32hqItHuZXLspFU5V42Y7/ff/Pt2t2vqM7R2IhG4/wPQqLt3iYfo04d0VTLm1Zti4W+fOTQW+/42Kpjgbhxpexi5CcfYusG6OkmL23VKbjenHEI85KAOgQj0I+9qJX3789nu+IuwzQJHJ8paCH/YtK3HvlEKOBnMjytCERr/q4ufvh7QmEEj6BhBJqUX9KUjPxINhZzGwRB7aVTR4hnEPASzv+huZKfjKPrd+CMzvBxqDqXJpO1aoEbJ0d2O3kTi2Z/5Uvc1rzPq67haTTlfi+NWWQUb+0ujOCA37AcKo5o/m1c2P+tE7rcqQOOlw1d7PmTkc/EVxTfETaP+9ZFkP+pV1oLaYkpQqRoT6z1lCAGXo5TsjnzV3ziMOl3rK/MxseNw1iomNhTu5XfzAizjGH+eMHeJHqquK+Leox6OnU0jjR25o/g/lU+jdxrJnAAq6BgE0Hrsa5e2NktUrnI3xrpmIpxmyxb8cA6mxi70yqUN3Ng1kTEVcmpyQw1GGGmqQM5xE4b8ytnaVUP0cgwTnZtdZ42CwQ0z87bft1sqhhLZzli3bDnvfZUqnrvNiYD63XHppwePPyBiUInV0DfRNbWI9nDg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
